services:
  rabbitmq:
    image: ${IMAGES}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./data:/var/lib/rabbitmq"
    #- "/etc/rabbitmq/conf.d/10-defaults.conf:./config/rabbitmq.conf"
    logging:
      driver: "json-file"
      options:
        # 日志文件大小
        max-size: "200m"
        # 最大日志文件数量
        max-file: "3"