
logs:
	docker-compose -f docker-compose.yaml logs -f

start:
	docker-compose -f docker-compose.yaml up -d

stop:
	docker-compose -f docker-compose.yaml down

clean:
	find . -name data -type d -exec rm -rf {} \;