services:
  #  redis服务
  redis-server:
    image: ${IMAGE}
    restart: "always"
    container_name: redis-server
    networks:
      - redis-net
    ports:
      - "${PORT}:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf
    # 使用该参数container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限
    privileged: true
    logging:
      driver: "json-file"
      options:
        # 日志文件大小
        max-size: "200m"
        # 最大日志文件数量
        max-file: "3"

#  # redis命令行,可以酌情使用,其实可以不用在启动一个服务,在执行命令行时直接进入到redis-server执行cli是一样的
#  redis-cli:
#    image: redis:6.2.7-alpine3.16
#    restart: "always"
#    container_name: redis-cli
#    command: /bin/sh -c 'redis-cli -h redis-server -p 6379 ping; while true; do sleep 20221011; done'
#    privileged: true
#    networks:
#      - redis-net

networks:
  redis-net:
