
logs:
	docker-compose -f docker-compose.yaml logs -f

start:
	docker-compose -f docker-compose.yaml up -d

stop:
	docker-compose -f docker-compose.yaml down

zookeeper:
	docker exec -it zookeeper1 bash

kafka:
	docker exec -it kafka1 bash

cli:
	docker exec -it cli bash