version: '3'
services:
  #  redis服务
  redis-server:
    image: redis:5.0.14-alpine
    restart: "always"
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf
    # 使用该参数container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限
    privileged: true

  # redis命令行
  redis-cli:
    image: redis:5.0.14-alpine
    restart: "always"
    container_name: redis-cli
    command: bash -c 'redis-cli -h redis-server -p 6379 ping; while true; do sleep 20220101; done'
    privileged: true